### ISSUE TITLE
spooled metrics not being processed

### ISSUE THREAD

**Issue by sjpalf** [grafana/carbon-relay-ng#373]
We had an upstream issue yesterday that caused metrics to be spooled to disk. However, after the issue was resolved, the spool files are not being processed. I have tried restarting the service to no effect. Is there any guidance on troubleshooting this issue?

**Comment by matthew-hollick** [comment]
We have observed that if carbon-relay-ng spools to disk the spool files are read and replayed to the target correctly but not cleaned up. Is this expected behaviour?

**Comment by Dieterbe** [comment]
> However, after the issue was resolved, the spool files are not being processed. 

Definitely not expected. They're not being read at all? what log level do you use and do the logs say anything about them?

> We have observed that if carbon-relay-ng spools to disk the spool files are read and replayed to the target correctly

Heh, this directly contradicts the OP. But it also the expected and most commonly seen behavior.
What crng versions do both of you use?

>  Is this expected behaviour?

I think cleanup of files is not implemented yet, but would need to investigate in the code to be sure.

**Comment by matthew-hollick** [comment]
:-) I'm aware that it contradicts @sjpalf - we work together and came back to review the behaviour and discovered that the data was consumed but found the lack of cleanup surprising.
I also want to say a quick thank you. We work for the UK HMRC where we have seen an unprecedented load on our web services over the last few weeks as businesses and self employed people have been signing up for COVID-19 support. Every single interaction with the platform creates many metrics, carbon-relay-ng has not dropped a single one (touch wood).

**Comment by Dieterbe** [comment]
yeah i think you just need to clean up the spool files manually.
