### ISSUE TITLE
Document best practice to achieve high availability

### ISSUE THREAD

**Issue by replay** [grafana/carbon-relay-ng#386]
We need to decide what's the best way to achieve high availability with carbon-relay-ng and document it.

Current candidates:
* hot instance and a cold standby which can get activated as soon as the hot one goes down
* run 2 instances concurrently and send all the data to both of them, so half of the data sent to us will then be too old

**Comment by Dieterbe** [comment]
not all senders are capable to duplicate their outgoing carbon streams.

senders like other relays can do this.
but typically not senders like statsd, system monitoring agents or applications
for those, we have to consider putting something in front. not sure what. HAProxy maybe?

**Comment by replay** [comment]
I added some documentation on how to achieve H/A here: https://github.com/grafana/metrictank/pull/1607/files
I think it makes sense to have it there because afaik this will get synced to the docs on our website and it's useful info for new users, right?  

Do you think I should basically copy these recommendations into the crng docs as well? Or otherwise maybe we should setup a mechanism to also sync crng docs onto the website, and then we wouldn't need to have crng recommendations in the MT repo.

**Comment by fitzoh** [comment]
That's a good point @replay...

I think I might also argue that it really doesn't make sense to have docs on sending metrics to grafana cloud within metrictank.

Maybe those should live within `carbon-relay-ng` docs  and/or grafana cloud docs?

**Comment by replay** [comment]
As far as I know  we need our cloud docs to get synced here https://github.com/grafana/website/tree/master/content/docs

Then they can be accessed here 
https://grafana.com/docs/cloud-graphite/

The README says this is done via a sync job
https://github.com/grafana/website/#updating-docs-content

I think we might want to also have some section in the cloud docs which has not been synced from the crng or mt repo, which is specifically talking about how to get data into GrafanaCloud. Or otherwise, if we want to continue syncing the docs from these repos, then the most appropriate place to put these docs would be the crng repo in my opinion.

**Comment by Dieterbe** [comment]
we need a place for grafanacloud graphite docs, and for simplicity we have chosen to use github.com/grafana/metrictank/docs/cloud for that, as some of it overlaps with the metrictank docs anyway and it's easier than having a separate repo just for docs.

Ultimately the most important thing is that on our website we have 1 central place for all gcloud graphite docs (including setting up the relay, and also HA for the relay), and that we can sync easily from our open source repo(s). Where those docs live is much less of a concern and I rather have Robby work on more important things at this point. We can always revisit this later once our docs start taking shape more and we have real problems to solve.

**Comment by replay** [comment]
Done in this PR (not merged yet): https://github.com/grafana/metrictank/pull/1607

**Comment by replay** [comment]
merged
