### ISSUE TITLE
Aggregation for count of matching metric series

### ISSUE THREAD

**Issue by matthew-hollick** [grafana/carbon-relay-ng#392]
Hi,
Is there a way to create a metric for the count of unique metric series seen in a bucket period?

ie 
if I have 100 servers each sending `servers.<server_name>.uptime` I want to create the metric `servers.count` with an expected value of 100.

**Comment by Dieterbe** [comment]
seems like you just need a count aggregator.
https://github.com/grafana/carbon-relay-ng/blob/master/docs/aggregation.md#functions

**Comment by matthew-hollick** [comment]
Brilliant.

I read the documentation "count | number of points/values seen (count of items in the bucket)" as meaning that the sum of all data points in all metric streams matched by the query would be calculated and returned.

ie
if I have 100 servers with a 1 second metric interval each sending `servers.<server_name>.uptime` with a 1 minute aggregation bucket size, I would get a result of 60,000.

Which, in hindsight, is really not all that useful :-)

Thanks again.
