### ISSUE TITLE
CircleCI checks not running for external PRs

### ISSUE THREAD

**Issue by fitzoh** [grafana/carbon-relay-ng#395]
Noticed in https://github.com/grafana/carbon-relay-ng/pull/393.

It looks like tests are being run from local branches, but not from forks

**Comment by woodsaj** [comment]
I have enabled "Build forked pull requests" in circleci, though forked pull requests dont have access to secrets. This shouldnt be an issue as the secrets are only needed for deploying, which only happens on commit to master
