### ISSUE TITLE
Parsing of env variables breaks the aggregator format definition

### ISSUE THREAD

**Issue by replay** [grafana/carbon-relay-ng#399]
the docs are showing [this example aggregator](https://github.com/grafana/carbon-relay-ng/blob/master/docs/aggregation.md#bucketing):
```
regex = '^servers\.(dc[0-9]+)\.(app|proxy)[0-9]+\.(.*)'
format = 'aggregates.$1.$2.$3.sum'
```

With [this PR](https://github.com/grafana/carbon-relay-ng/pull/393/files#diff-65c8657132046da9d4d53efe48307295R67) we are expanding os env variables in the crng config. But this expansion tries to replace the strings `$1`,`$2`,`$3`, resulting in the format value `aggregates...sum`. I also didn't find a good way of escaping the `$` in the config

**Comment by Dieterbe** [comment]
How about we simply pass them through in the expandVars function ?
