### ISSUE TITLE
Debian/Ubuntu Systemd service-file has wrong mode (is executable).

### ISSUE THREAD

**Issue by JohanElmis** [grafana/carbon-relay-ng#440]
On a Debian Bionic (18.04), I get this in dmesg during server boot.
```:[    7.660894] systemd[1]: Configuration file /lib/systemd/system/carbon-relay-ng.service is marked executable. Please remove executable permission bits. Proceeding anyway.```

This is the only file in that dir that is executable.
```-rwxr-xr-x 1 root root 476 Jul 10 14:56 /lib/systemd/system/carbon-relay-ng.service*```

But the file is not executable in the examples dir - and the Makefile is using install - which should preserve the setting.
So I don't get it.
Maybe it should be installed with:
```install -m 0644 examples/carbon-relay-ng.service debian/lib/systemd/system```

Leaving this to the maintainer - and others to decide. I can create a PR - but it should probably be applied to more than just the deb: build-linux - section in that case.

**Comment by Dieterbe** [comment]
strange. never heard this issue before.
maybe somebody in @grafana/infra-team knows what is the proper way to copy config files with the correct permissions

**Comment by tlo8640** [comment]
Hello,
the rpm has the same problem, unit file is executable. It should be fixed in rpm package, too.
Thank you very much
