### ISSUE TITLE
No way to disable internal statistics?

### ISSUE THREAD

**Issue by dr3amville** [grafana/carbon-relay-ng#455]
Hi, I am utilizing the relay to forward metric data to two graphite endpoints on two different InfluxDB nodes for some testing. I noticed a bunch of internal carbon-relay-ng graphite-based metrics also showing up that don't fall in line in my schema and I would rather not have them. Is there a way to disable them? I have been unable to find this. 

They look something like this (my separator is a '_' so probably '.' separated normally):
`service_is_carbon-relay-ng_instance_is_ng_relay_<relay-hostname>_mtype_is_count_dest_is_carbon-default_<destination-ip-port>_unit_is_Metric_what_is_FlushSize_type_is_ticker_orig_unit_is_B`

These repeat for durationFlush, durationWrite, Err, Metric_action, etc. I would just like it to stop sending these internal metrics to the destinations defined.

If it helps, my configuration looks like this:
```instance = "ng_relay_dev-carbon-relay01"

max_procs = 2

listen_addr = "0.0.0.0:2003"
admin_addr = "0.0.0.0:2006"
http_addr = "0.0.0.0:8081"

spool_dir = "spool"
pid_file = "/opt/run/carbon-relay-ng.pid"
log_level = "info"
bad_metrics_max_age = "24h"
validation_level_legacy = "medium"
validation_level_m20 = "medium"

validate_order = false

plain_read_timeout = "2m"
pickle_read_timeout = "2m"

[init]
cmds = [
     'addRoute sendAllMatch carbon-default  <dst-ip1>:2003 spool=false pickle=false',
     'addRoute sendAllMatch carbon-default  <dst-ip2>:2003 spool=false pickle=false']


[instrumentation]
# in addition to serving internal metrics via expvar, you can optionally send em to graphite
graphite_addr = "127.0.0.1:2003"  # localhost:2003
graphite_interval = 60000  # in ms
```

As a note I just tried adding the following and it seems to have worked, in the cmds, `'addBlack regex .*carbon.*',` but it seems to be a weird way of doing this, I'm sure there is a config that can be set?

**Comment by Dieterbe** [comment]
> As a note I just tried adding the following and it seems to have worked, in the cmds, 'addBlack regex .*carbon.*', but it seems to be a weird way of doing this, I'm sure there is a config that can be set?

using the blacklist is a good approach. how does #456 look ?

**Comment by dr3amville** [comment]
@Dieterbe That looks good, wish there was a way to disable them but that will do the job, thanks!
