### ISSUE TITLE
Thoughts about removing Blacklist terminology

### ISSUE THREAD

**Issue by matthew-hollick** [grafana/carbon-relay-ng#459]
Good morning,

I am currently engaged by a UK government organisation to, as part of a team, provide telemetry services for their web presence.
Carbon-relay-ng is part of our stack and we like it loads - Thanks!
Recently we have been asked to consider the terminology used in the services that we deploy and work to make it more inclusive.
Some examples:
- Use "Main" rather than "Master" in git repositories
- ~~Use "Follower" rather than "Slave" in cluster topologies~~ Edit: see comment from Grafana Docs Squad.
- Use the term "Blocklist" rather than "Blacklist" in filter rules

As part of this work I would like to know what your thoughts might be about adding a synonym for Blacklist in the carbon-relay-ng configuration. I appreciate that changing the name of things can be difficult, especially when coping with upgrading existing deployments. I also appreciate that this would have the potential to make documentation more complex.

Cheers!

**Comment by Dieterbe** [comment]
I support this idea. Haven't had time myself to make it happen, but if somebody puts in the PR's, we can do it, one step at a time.
the blocklist change for example, i would recommend it not just be an equal synonym but promote the new term and deprecate the old one (but still allow it to not break existing installs until enough time has passed)

**Comment by osg-grafana** [comment]
Please align with Grafana style guide at https://github.com/grafana/grafana/blob/main/contribute/style-guides/documentation-style-guide.md#primary-and-secondary and https://github.com/grafana/grafana/blob/main/contribute/style-guides/documentation-style-guide.md#allowing-and-blocking.

**Comment by achatterjee-grafana** [comment]
I second @osg-grafana's previous comment. Refer to and use the suggestions from the Grafana style guide to make the necessary changes.

I will also recommend main/secondary and would prefer NOT to use the word "follower".

Totally on board with using the term "blocklist"(https://github.com/grafana/grafana/blob/main/contribute/style-guides/documentation-style-guide.md#allowing-and-blocking). Apart from being a neutral term, it is also appropriate for use by an Internet company like Grafana.

Something to consider also, for our linter wordlist.

**Comment by KMiller-Grafana** [comment]
I'm doing an assessment of the repo and will report back what I find for use of the offensive term "blacklist." The assessment will identify what needs to be changed.

**Comment by Dieterbe** [comment]
no need to "do/write an assesment".
a simple grep of the repo makes it obvious where the term is used.

**Comment by KMiller-Grafana** [comment]
@Dieterbe, Yup, grep used.  I recorded the results; it forms a checklist to make sure the offensive term is changed everywhere.

**Comment by matthew-hollick** [comment]
Awesome stuff!
