### ISSUE TITLE
Better handling when aggregationFile isn't defined

### ISSUE THREAD

**Issue by indygriffiths** [grafana/carbon-relay-ng#469]
If the new `aggregationFile` option isn't defined, `carbon-relay-ng` fails to start with a cryptic error message:

```
2021-07-01 22:49:45.813 [ERROR] NewGrafanaNetConfig: could not read aggregationFile "": read .: is a directory
2021-07-01 22:49:45.815 [ERROR] error adding route 'grafanaNet'
```

Ideally if the option isn't defined it could explain what the error is and link to the docs within the repo, or have it create a default storage-aggregation.conf file automatically. 

For context, our `carbon-relay-ng` package was upgraded automatically which broke our metric pipeline as this option wasn't defined (aware it shouldn't have jumped up a major version so that's on us). I've also raised [a post on the Grafana fourm](https://community.grafana.com/t/carbon-relay-ng-docs-when-viewing-a-graphite-instance-are-out-of-date/49843) as the docs for setting up `carbon-relay-ng` when viewing a Grafana Cloud Graphite instance are now out-of-date if you're using the latest version.

**Comment by Dieterbe** [comment]
you're absolutely right.
* the error message needs to be improved. PR coming.
* the changelog wasn't clear enough - i have updated it now https://github.com/grafana/carbon-relay-ng/releases/tag/v1.0
* the docs are still rolling out. the portal UI still needs updating, i expect this to be complete next week.

Sorry for the confusion, this should all be squared away by end of next week.
