### ISSUE TITLE
Blocklist does not work

### ISSUE THREAD

**Issue by nikobearrr** [grafana/carbon-relay-ng#486]
Running grafana/carbon-relay-ng:1.1 and following the guide here: https://github.com/grafana/carbon-relay-ng/blob/master/docs/config.md#Blocklist does not show anything in the UI and logs that has been blocklisted.
When I revert the change `blocklist` to `blacklist` then both the logs and the UI show my list of blocked items.

EDIT: I did my research after posting this and I can see that it is not yet released. But the docs on which can be found on `master` say that I should use `blocklist`. It is a bit confusing.

**Comment by Dieterbe** [comment]
Hi Nikola, that is a good point indeed. the docs reflect master which isn't released yet.
I expect this will work itself out over the next couple days to a week, as we are working on cutting a new release shortly.
Sorry for the confusion..

**Comment by nikobearrr** [comment]
That sounds good. 
Thank you for all the great work

**Comment by Dieterbe** [comment]
fyi @nikobearrr i released v1.2 : https://github.com/grafana/carbon-relay-ng/releases/tag/v1.2 hope it works well for you this time!
