### ISSUE TITLE
Release Binaries are deleted on CircleCI

### ISSUE THREAD

**Issue by mcdermottsailthru** [grafana/carbon-relay-ng#493]
After 30 days, all artifacts associated with a build automatically expire. Since this run is over 30 days old, the artifacts may have been deleted.

Can we copy releases to github?

**Comment by jesusvazquez** [comment]
Hello, thanks for reporting this.

I just released v1.2.1 with a few changes on CI and now binaries will be appended to the release.

Sorry for the delay delivering this.
