### ISSUE TITLE
Version 1.4.4 did not successfully release

### ISSUE THREAD

**Issue by jfharden** [grafana/carbon-relay-ng#541]
You very kindly merged my PR to update some of the go build dependencies (https://github.com/grafana/carbon-relay-ng/pull/538) and created a changelog for the release (https://github.com/grafana/carbon-relay-ng/pull/540) but since the merge 1.4.4 has not been successfully released: https://github.com/grafana/carbon-relay-ng/runs/15394626569

**Comment by jesusvazquez** [comment]
Hey @jfharden thanks for reporting.

It seems that the CI job timed out. I just retried it and the binaries are up https://github.com/grafana/carbon-relay-ng/releases/tag/v1.4.4

Closing as done!
