### ISSUE TITLE
The dependency toki isn't licensed

### ISSUE THREAD

**Issue by asponzan** [grafana/carbon-relay-ng#551]
In reviewing the dependencies for carbon-relay-ng we discovered that the upstream of toki, https://github.com/taylorchu/toki, doesn't have a declared license. Does the project have explicit permission to use this code?

**Comment by asponzan** [comment]
Understanding that there hasn't been movement on https://github.com/taylorchu/toki/issues/2 are there plans to mitigate this copyright issue?

**Comment by npazosmendez** [comment]
This should be resolved now, thank you for your patience!  🙂 See https://github.com/taylorchu/toki/commit/36c157adcc65b5cfec7781167acbfb4ea240d469
